[build]
  publish = "."

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy-policy/index.html"
  status = 200

[[redirects]]
  from = "/terms-of-use"
  to = "/terms-of-use/index.html"
  status = 200

[[redirects]]
  from = "/electronic-consent"
  to = "/electronic-consent/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
